"""The MCPymol bridge server — entry point and public surface.

This module is what the MCP client launches (``mcpymol = mcpymol.server:main``).
Importing it pulls in every tool module, and importing a tool module is what
registers its tools on the shared :data:`mcpymol.app.mcp` application, so the
imports below are load-bearing rather than decorative.

The implementation lives in focused modules:

========================  ====================================================
``mcpymol.app``           the shared FastMCP application object
``mcpymol.bridge``        the socket protocol to the in-PyMOL plugin
``mcpymol.structures``    fetching/loading structures, session introspection
``mcpymol.primitives``    one thin tool per ``pymol.cmd`` function
``mcpymol.views``         the high-level ``*_view`` scene presets
``mcpymol.conservation``  MSA + Shannon entropy + ``conservation_view``
``mcpymol.printing``      watertight STL export for 3D printing
========================  ====================================================

Every name is re-exported here so ``from mcpymol.server import ligand_view``
keeps working. New code should import from the owning module instead — and a
test patching an internal *must*, because patching a re-export rebinds only
this module's name, not the one the function actually calls.
"""

from mcpymol.app import (
    mcp,
)
from mcpymol.bridge import (
    _DEFAULT_TIMEOUT,
    _RECV_CHUNK,
    _SLOW_OP_TIMEOUT,
    HOST,
    PORT,
    _call,
    send_request,
)
from mcpymol.comparison import (
    _DEFAULT_DEVIATION_CEILING,
    _TOP_N_SHIFTED,
    _distance,
    _match_residues,
    _parse_ca_coords,
    _resi_sort_key,
    superposition_view,
)
from mcpymol.conservation import (
    _AA_ALPHABET,
    MMSEQS_URL,
    _compute_shannon_entropy,
    _conservation_cache,
    _parse_a3m,
    _run_mmseqs2,
    conservation_view,
)
from mcpymol.primitives import (
    align,
    alter,
    alter_state,
    angle,
    as_tool,
    backward,
    bond,
    cartoon,
    cd,
    center,
    clip,
    color,
    create,
    delete,
    deselect,
    dihedral,
    distance,
    draw,
    execute_pymol_command,
    extract,
    fab,
    forward,
    fragment,
    frame,
    full_screen,
    h_add,
    h_fill,
    help,
    hide,
    intra_fit,
    intra_rms,
    isomesh,
    isosurface,
    label,
    ls,
    move,
    mplay,
    mpng,
    mset,
    mstop,
    orient,
    png,
    pwd,
    ray,
    rebuild,
    refresh,
    remove,
    reset,
    rock,
    save,
    scene,
    scene_order,
    sculpt_activate,
    sculpt_deactivate,
    sculpt_iterate,
    select,
    set_setting,
    set_symmetry,
    show,
    spectrum,
    spheroid,
    super_tool,
    symexp,
    system,
    turn,
    unbond,
    util_cbab,
    util_cbac,
    util_cbag,
    util_cbak,
    util_cbam,
    util_cbao,
    util_cbap,
    util_cbas,
    util_cbaw,
    util_cbay,
    util_cbc,
    util_chainbow,
    util_color_by_element,
    util_color_secondary,
    util_rainbow,
    util_ss,
    viewport,
    zoom,
)
from mcpymol.printing import (
    _PRINT_DEPS_HINT,
    _parse_groups,
    _repair_to_stl,
    print_export,
    print_ribbon_view,
)
from mcpymol.rendering import (
    _PNG_APPEAR_TIMEOUT,
    _PNG_EOF,
    DEFAULT_RENDER_HEIGHT,
    DEFAULT_RENDER_WIDTH,
    MAX_INLINE_IMAGE_BYTES,
    _read_complete_png,
    render,
    turntable,
)
from mcpymol.structures import (
    _GHOST_HEART_GREENS,
    _UNIPROT_RE,
    ALPHAFOLD_URL,
    DEFAULT_ALPHAFOLD_VERSION,
    DEFAULT_MULTIMER_CUTOFF,
    _alphafold_accession,
    _apply_ghost_heart,
    _apply_multimer_heuristic,
    _download_alphafold,
    fetch_alphafold,
    fetch_structure,
    list_chains,
    list_ligands,
    list_objects,
    load_structure,
)
from mcpymol.views import (
    _PB_SUBPROCESS_TIMEOUT,
    _PLDDT_BANDS,
    _read_ca_bfactors,
    bfactor_view,
    cinematic_view,
    crosslink_view,
    electrostatic_view,
    hydrophobic_surface_view,
    interface_view,
    ligand_view,
    mutation_view,
    pharmacophore_view,
    plddt_view,
    pocket_view,
    pointillist_view,
    poisson_boltzmann_view,
    putty_view,
    textbook_view,
)

__all__ = [
    "ALPHAFOLD_URL",
    "DEFAULT_ALPHAFOLD_VERSION",
    "DEFAULT_MULTIMER_CUTOFF",
    "DEFAULT_RENDER_HEIGHT",
    "DEFAULT_RENDER_WIDTH",
    "HOST",
    "MAX_INLINE_IMAGE_BYTES",
    "MMSEQS_URL",
    "PORT",
    "_AA_ALPHABET",
    "_DEFAULT_DEVIATION_CEILING",
    "_DEFAULT_TIMEOUT",
    "_GHOST_HEART_GREENS",
    "_PB_SUBPROCESS_TIMEOUT",
    "_PLDDT_BANDS",
    "_PNG_APPEAR_TIMEOUT",
    "_PNG_EOF",
    "_PRINT_DEPS_HINT",
    "_RECV_CHUNK",
    "_SLOW_OP_TIMEOUT",
    "_TOP_N_SHIFTED",
    "_UNIPROT_RE",
    "_alphafold_accession",
    "_apply_ghost_heart",
    "_apply_multimer_heuristic",
    "_call",
    "_compute_shannon_entropy",
    "_conservation_cache",
    "_distance",
    "_download_alphafold",
    "_match_residues",
    "_parse_a3m",
    "_parse_ca_coords",
    "_parse_groups",
    "_read_ca_bfactors",
    "_read_complete_png",
    "_repair_to_stl",
    "_resi_sort_key",
    "_run_mmseqs2",
    "align",
    "alter",
    "alter_state",
    "angle",
    "as_tool",
    "backward",
    "bfactor_view",
    "bond",
    "cartoon",
    "cd",
    "center",
    "cinematic_view",
    "clip",
    "color",
    "conservation_view",
    "create",
    "crosslink_view",
    "delete",
    "deselect",
    "dihedral",
    "distance",
    "draw",
    "electrostatic_view",
    "execute_pymol_command",
    "extract",
    "fab",
    "fetch_alphafold",
    "fetch_structure",
    "forward",
    "fragment",
    "frame",
    "full_screen",
    "h_add",
    "h_fill",
    "help",
    "hide",
    "hydrophobic_surface_view",
    "interface_view",
    "intra_fit",
    "intra_rms",
    "isomesh",
    "isosurface",
    "label",
    "ligand_view",
    "list_chains",
    "list_ligands",
    "list_objects",
    "load_structure",
    "ls",
    "main",
    "mcp",
    "move",
    "mplay",
    "mpng",
    "mset",
    "mstop",
    "mutation_view",
    "orient",
    "pharmacophore_view",
    "plddt_view",
    "png",
    "pocket_view",
    "pointillist_view",
    "poisson_boltzmann_view",
    "print_export",
    "print_ribbon_view",
    "putty_view",
    "pwd",
    "ray",
    "rebuild",
    "refresh",
    "remove",
    "render",
    "reset",
    "rock",
    "save",
    "scene",
    "scene_order",
    "sculpt_activate",
    "sculpt_deactivate",
    "sculpt_iterate",
    "select",
    "send_request",
    "set_setting",
    "set_symmetry",
    "show",
    "spectrum",
    "spheroid",
    "super_tool",
    "superposition_view",
    "symexp",
    "system",
    "textbook_view",
    "turn",
    "turntable",
    "unbond",
    "util_cbab",
    "util_cbac",
    "util_cbag",
    "util_cbak",
    "util_cbam",
    "util_cbao",
    "util_cbap",
    "util_cbas",
    "util_cbaw",
    "util_cbay",
    "util_cbc",
    "util_chainbow",
    "util_color_by_element",
    "util_color_secondary",
    "util_rainbow",
    "util_ss",
    "viewport",
    "zoom",
]


def main():
    mcp.run()


if __name__ == "__main__":
    main()
